In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b=np.array([[11,12,13],[14,15,16],[17,18,19]])


In [6]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [7]:
add=np.add(a,b)

In [8]:
add

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [9]:
multiply=np.multiply(a,b)

In [10]:
multiply

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [11]:
transpose=np.transpose(a)

In [12]:
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
A="Globallyacclaimededucationresearchinscienceengineeringmanagementhumanities"
A=A.lower()
A=sorted(A)
A="".join(A)
print(A)

aaaaaaaabccccccddeeeeeeeeeeeegggghhiiiiiiiillllmmmmnnnnnnnnnoorrrssstttuuy


In [27]:
test_str = "sud, is best : for ! rrrr ;"
print("The original string is : " + test_str)
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for ele in test_str:
    if ele in punc:
        test_str = test_str.replace(ele, "")
print("The string after punctuation filter : " + test_str)

The original string is : sud, is best : for ! rrrr ;
The string after punctuation filter : sud is best  for  rrrr 
